sudo: required
services:
  - docker

before_install:
  - docker build -t selimdincer/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true selimdincer/docker-react npm run test

deploy:
  provide: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-871834746074"
  bucket_path: "docker-react"
  on:
    brach: master
  acces_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"  

